# Generated by Django 2.1.5 on 2023-01-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230105_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default=1, to='shop.Category'),
        ),
    ]
